package cn.net.guu.cms.model;

public class About {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_cms_about.about_id
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    private String aboutId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_cms_about.company_name
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_cms_about.company_en
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    private String companyEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_cms_about.company_address
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_cms_about.image_path
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_cms_about.contact_person
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_cms_about.company_email
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    private String companyEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_cms_about.company_fax
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    private String companyFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_cms_about.company_phone
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    private String companyPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_cms_about.company_desc
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    private String companyDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_cms_about.about_id
     *
     * @return the value of guu_cms_about.about_id
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public String getAboutId() {
        return aboutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_cms_about.about_id
     *
     * @param aboutId the value for guu_cms_about.about_id
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public void setAboutId(String aboutId) {
        this.aboutId = aboutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_cms_about.company_name
     *
     * @return the value of guu_cms_about.company_name
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_cms_about.company_name
     *
     * @param companyName the value for guu_cms_about.company_name
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_cms_about.company_en
     *
     * @return the value of guu_cms_about.company_en
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public String getCompanyEn() {
        return companyEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_cms_about.company_en
     *
     * @param companyEn the value for guu_cms_about.company_en
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public void setCompanyEn(String companyEn) {
        this.companyEn = companyEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_cms_about.company_address
     *
     * @return the value of guu_cms_about.company_address
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_cms_about.company_address
     *
     * @param companyAddress the value for guu_cms_about.company_address
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_cms_about.image_path
     *
     * @return the value of guu_cms_about.image_path
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_cms_about.image_path
     *
     * @param imagePath the value for guu_cms_about.image_path
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_cms_about.contact_person
     *
     * @return the value of guu_cms_about.contact_person
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_cms_about.contact_person
     *
     * @param contactPerson the value for guu_cms_about.contact_person
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_cms_about.company_email
     *
     * @return the value of guu_cms_about.company_email
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public String getCompanyEmail() {
        return companyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_cms_about.company_email
     *
     * @param companyEmail the value for guu_cms_about.company_email
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_cms_about.company_fax
     *
     * @return the value of guu_cms_about.company_fax
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public String getCompanyFax() {
        return companyFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_cms_about.company_fax
     *
     * @param companyFax the value for guu_cms_about.company_fax
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public void setCompanyFax(String companyFax) {
        this.companyFax = companyFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_cms_about.company_phone
     *
     * @return the value of guu_cms_about.company_phone
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public String getCompanyPhone() {
        return companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_cms_about.company_phone
     *
     * @param companyPhone the value for guu_cms_about.company_phone
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_cms_about.company_desc
     *
     * @return the value of guu_cms_about.company_desc
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public String getCompanyDesc() {
        return companyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_cms_about.company_desc
     *
     * @param companyDesc the value for guu_cms_about.company_desc
     *
     * @mbggenerated Sat Jan 31 03:14:01 CST 2015
     */
    public void setCompanyDesc(String companyDesc) {
        this.companyDesc = companyDesc;
    }

	@Override
	public String toString()
	{
		return "About [aboutId=" + aboutId + ", companyName=" + companyName + ", companyEn=" + companyEn + ", companyAddress=" + companyAddress
				+ ", imagePath=" + imagePath + ", contactPerson=" + contactPerson + ", companyEmail=" + companyEmail + ", companyFax=" + companyFax
				+ ", companyPhone=" + companyPhone + ", companyDesc=" + companyDesc + "]";
	}
    
    
}