package cn.net.guu.system.model;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_config.config_id
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    private String configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_config.config_name
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_config.config_value
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_config.express
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    private String express;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_config.status
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_config.description
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_config.default_value
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    private String defaultValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_config.template_id
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    private String templateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_config.config_id
     *
     * @return the value of guu_config.config_id
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public String getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_config.config_id
     *
     * @param configId the value for guu_config.config_id
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public void setConfigId(String configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_config.config_name
     *
     * @return the value of guu_config.config_name
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_config.config_name
     *
     * @param configName the value for guu_config.config_name
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public void setConfigName(String configName) {
        this.configName = configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_config.config_value
     *
     * @return the value of guu_config.config_value
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_config.config_value
     *
     * @param configValue the value for guu_config.config_value
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_config.express
     *
     * @return the value of guu_config.express
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public String getExpress() {
        return express;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_config.express
     *
     * @param express the value for guu_config.express
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public void setExpress(String express) {
        this.express = express;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_config.status
     *
     * @return the value of guu_config.status
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_config.status
     *
     * @param status the value for guu_config.status
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_config.description
     *
     * @return the value of guu_config.description
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_config.description
     *
     * @param description the value for guu_config.description
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_config.default_value
     *
     * @return the value of guu_config.default_value
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_config.default_value
     *
     * @param defaultValue the value for guu_config.default_value
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_config.template_id
     *
     * @return the value of guu_config.template_id
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_config.template_id
     *
     * @param templateId the value for guu_config.template_id
     *
     * @mbggenerated Sat Nov 07 12:40:23 CST 2015
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId;
    }
}