package cn.net.guu.system.model;

import java.util.Date;

public class SysAccess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access.access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String accessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access.access_name
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String accessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access.access_code
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String accessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access.creat_time
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access.module
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String module;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access.access_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Integer accessStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access.issys
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Integer issys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access.remark
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access.access_id
     *
     * @return the value of guu_sys_access.access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getAccessId() {
        return accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access.access_id
     *
     * @param accessId the value for guu_sys_access.access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setAccessId(String accessId) {
        this.accessId = accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access.access_name
     *
     * @return the value of guu_sys_access.access_name
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getAccessName() {
        return accessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access.access_name
     *
     * @param accessName the value for guu_sys_access.access_name
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setAccessName(String accessName) {
        this.accessName = accessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access.access_code
     *
     * @return the value of guu_sys_access.access_code
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getAccessCode() {
        return accessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access.access_code
     *
     * @param accessCode the value for guu_sys_access.access_code
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setAccessCode(String accessCode) {
        this.accessCode = accessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access.creat_time
     *
     * @return the value of guu_sys_access.creat_time
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access.creat_time
     *
     * @param creatTime the value for guu_sys_access.creat_time
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access.module
     *
     * @return the value of guu_sys_access.module
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access.module
     *
     * @param module the value for guu_sys_access.module
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access.access_status
     *
     * @return the value of guu_sys_access.access_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Integer getAccessStatus() {
        return accessStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access.access_status
     *
     * @param accessStatus the value for guu_sys_access.access_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setAccessStatus(Integer accessStatus) {
        this.accessStatus = accessStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access.issys
     *
     * @return the value of guu_sys_access.issys
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Integer getIssys() {
        return issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access.issys
     *
     * @param issys the value for guu_sys_access.issys
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setIssys(Integer issys) {
        this.issys = issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access.remark
     *
     * @return the value of guu_sys_access.remark
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access.remark
     *
     * @param remark the value for guu_sys_access.remark
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}