package cn.net.guu.system.model;

public class SysAccessResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access_resources.access_resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String accessResourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access_resources.access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String accessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access_resources.resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_access_resources.ar_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Integer arStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access_resources.access_resources_id
     *
     * @return the value of guu_sys_access_resources.access_resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getAccessResourcesId() {
        return accessResourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access_resources.access_resources_id
     *
     * @param accessResourcesId the value for guu_sys_access_resources.access_resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setAccessResourcesId(String accessResourcesId) {
        this.accessResourcesId = accessResourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access_resources.access_id
     *
     * @return the value of guu_sys_access_resources.access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getAccessId() {
        return accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access_resources.access_id
     *
     * @param accessId the value for guu_sys_access_resources.access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setAccessId(String accessId) {
        this.accessId = accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access_resources.resources_id
     *
     * @return the value of guu_sys_access_resources.resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access_resources.resources_id
     *
     * @param resourcesId the value for guu_sys_access_resources.resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_access_resources.ar_status
     *
     * @return the value of guu_sys_access_resources.ar_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Integer getArStatus() {
        return arStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_access_resources.ar_status
     *
     * @param arStatus the value for guu_sys_access_resources.ar_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setArStatus(Integer arStatus) {
        this.arStatus = arStatus;
    }
}