package cn.net.guu.system.model;

import java.util.ArrayList;
import java.util.List;

import cn.net.guu.core.mappers.BaseExample;

public class SysAccessResourcesExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public SysAccessResourcesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAccessResourcesIdIsNull() {
            addCriterion("access_resources_id is null");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdIsNotNull() {
            addCriterion("access_resources_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdEqualTo(String value) {
            addCriterion("access_resources_id =", value, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdNotEqualTo(String value) {
            addCriterion("access_resources_id <>", value, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdGreaterThan(String value) {
            addCriterion("access_resources_id >", value, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdGreaterThanOrEqualTo(String value) {
            addCriterion("access_resources_id >=", value, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdLessThan(String value) {
            addCriterion("access_resources_id <", value, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdLessThanOrEqualTo(String value) {
            addCriterion("access_resources_id <=", value, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdLike(String value) {
            addCriterion("access_resources_id like", value, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdNotLike(String value) {
            addCriterion("access_resources_id not like", value, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdIn(List<String> values) {
            addCriterion("access_resources_id in", values, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdNotIn(List<String> values) {
            addCriterion("access_resources_id not in", values, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdBetween(String value1, String value2) {
            addCriterion("access_resources_id between", value1, value2, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessResourcesIdNotBetween(String value1, String value2) {
            addCriterion("access_resources_id not between", value1, value2, "accessResourcesId");
            return (Criteria) this;
        }

        public Criteria andAccessIdIsNull() {
            addCriterion("access_id is null");
            return (Criteria) this;
        }

        public Criteria andAccessIdIsNotNull() {
            addCriterion("access_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccessIdEqualTo(String value) {
            addCriterion("access_id =", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdNotEqualTo(String value) {
            addCriterion("access_id <>", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdGreaterThan(String value) {
            addCriterion("access_id >", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdGreaterThanOrEqualTo(String value) {
            addCriterion("access_id >=", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdLessThan(String value) {
            addCriterion("access_id <", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdLessThanOrEqualTo(String value) {
            addCriterion("access_id <=", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdLike(String value) {
            addCriterion("access_id like", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdNotLike(String value) {
            addCriterion("access_id not like", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdIn(List<String> values) {
            addCriterion("access_id in", values, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdNotIn(List<String> values) {
            addCriterion("access_id not in", values, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdBetween(String value1, String value2) {
            addCriterion("access_id between", value1, value2, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdNotBetween(String value1, String value2) {
            addCriterion("access_id not between", value1, value2, "accessId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdIsNull() {
            addCriterion("resources_id is null");
            return (Criteria) this;
        }

        public Criteria andResourcesIdIsNotNull() {
            addCriterion("resources_id is not null");
            return (Criteria) this;
        }

        public Criteria andResourcesIdEqualTo(String value) {
            addCriterion("resources_id =", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdNotEqualTo(String value) {
            addCriterion("resources_id <>", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdGreaterThan(String value) {
            addCriterion("resources_id >", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdGreaterThanOrEqualTo(String value) {
            addCriterion("resources_id >=", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdLessThan(String value) {
            addCriterion("resources_id <", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdLessThanOrEqualTo(String value) {
            addCriterion("resources_id <=", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdLike(String value) {
            addCriterion("resources_id like", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdNotLike(String value) {
            addCriterion("resources_id not like", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdIn(List<String> values) {
            addCriterion("resources_id in", values, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdNotIn(List<String> values) {
            addCriterion("resources_id not in", values, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdBetween(String value1, String value2) {
            addCriterion("resources_id between", value1, value2, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdNotBetween(String value1, String value2) {
            addCriterion("resources_id not between", value1, value2, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andArStatusIsNull() {
            addCriterion("ar_status is null");
            return (Criteria) this;
        }

        public Criteria andArStatusIsNotNull() {
            addCriterion("ar_status is not null");
            return (Criteria) this;
        }

        public Criteria andArStatusEqualTo(Integer value) {
            addCriterion("ar_status =", value, "arStatus");
            return (Criteria) this;
        }

        public Criteria andArStatusNotEqualTo(Integer value) {
            addCriterion("ar_status <>", value, "arStatus");
            return (Criteria) this;
        }

        public Criteria andArStatusGreaterThan(Integer value) {
            addCriterion("ar_status >", value, "arStatus");
            return (Criteria) this;
        }

        public Criteria andArStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("ar_status >=", value, "arStatus");
            return (Criteria) this;
        }

        public Criteria andArStatusLessThan(Integer value) {
            addCriterion("ar_status <", value, "arStatus");
            return (Criteria) this;
        }

        public Criteria andArStatusLessThanOrEqualTo(Integer value) {
            addCriterion("ar_status <=", value, "arStatus");
            return (Criteria) this;
        }

        public Criteria andArStatusIn(List<Integer> values) {
            addCriterion("ar_status in", values, "arStatus");
            return (Criteria) this;
        }

        public Criteria andArStatusNotIn(List<Integer> values) {
            addCriterion("ar_status not in", values, "arStatus");
            return (Criteria) this;
        }

        public Criteria andArStatusBetween(Integer value1, Integer value2) {
            addCriterion("ar_status between", value1, value2, "arStatus");
            return (Criteria) this;
        }

        public Criteria andArStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("ar_status not between", value1, value2, "arStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 23 23:14:26 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_sys_access_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}