package cn.net.guu.system.model;


public class SysAuthorityResources  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority_resources.authority_res_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String authorityResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority_resources.authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String authorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority_resources.resources_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority_resources.ar_status
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private Integer arStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority_resources.authority_res_id
     *
     * @return the value of guu_sys_authority_resources.authority_res_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getAuthorityResId() {
        return authorityResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority_resources.authority_res_id
     *
     * @param authorityResId the value for guu_sys_authority_resources.authority_res_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setAuthorityResId(String authorityResId) {
        this.authorityResId = authorityResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority_resources.authority_id
     *
     * @return the value of guu_sys_authority_resources.authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority_resources.authority_id
     *
     * @param authorityId the value for guu_sys_authority_resources.authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority_resources.resources_id
     *
     * @return the value of guu_sys_authority_resources.resources_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority_resources.resources_id
     *
     * @param resourcesId the value for guu_sys_authority_resources.resources_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority_resources.ar_status
     *
     * @return the value of guu_sys_authority_resources.ar_status
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public Integer getArStatus() {
        return arStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority_resources.ar_status
     *
     * @param arStatus the value for guu_sys_authority_resources.ar_status
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setArStatus(Integer arStatus) {
        this.arStatus = arStatus;
    }
}