package cn.net.guu.system.model;

public class SysAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority.authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String authorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority.authority_code
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String authorityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority.authority_name
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String authorityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority.authority_desc
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String authorityDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority.module
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String module;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority.authority_status
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private Integer authorityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_authority.issys
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private Integer issys;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority.authority_id
     *
     * @return the value of guu_sys_authority.authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority.authority_id
     *
     * @param authorityId the value for guu_sys_authority.authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority.authority_code
     *
     * @return the value of guu_sys_authority.authority_code
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getAuthorityCode() {
        return authorityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority.authority_code
     *
     * @param authorityCode the value for guu_sys_authority.authority_code
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setAuthorityCode(String authorityCode) {
        this.authorityCode = authorityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority.authority_name
     *
     * @return the value of guu_sys_authority.authority_name
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority.authority_name
     *
     * @param authorityName the value for guu_sys_authority.authority_name
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority.authority_desc
     *
     * @return the value of guu_sys_authority.authority_desc
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getAuthorityDesc() {
        return authorityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority.authority_desc
     *
     * @param authorityDesc the value for guu_sys_authority.authority_desc
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setAuthorityDesc(String authorityDesc) {
        this.authorityDesc = authorityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority.module
     *
     * @return the value of guu_sys_authority.module
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority.module
     *
     * @param module the value for guu_sys_authority.module
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority.authority_status
     *
     * @return the value of guu_sys_authority.authority_status
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public Integer getAuthorityStatus() {
        return authorityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority.authority_status
     *
     * @param authorityStatus the value for guu_sys_authority.authority_status
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setAuthorityStatus(Integer authorityStatus) {
        this.authorityStatus = authorityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_authority.issys
     *
     * @return the value of guu_sys_authority.issys
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public Integer getIssys() {
        return issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_authority.issys
     *
     * @param issys the value for guu_sys_authority.issys
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setIssys(Integer issys) {
        this.issys = issys;
    }
}