package cn.net.guu.system.model;

import java.util.Date;

public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role.role_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role.role_name
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role.role_code
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role.creat_user
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String creatUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role.creat_time
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role.role_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Integer roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role.issys
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Integer issys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role.remark
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role.role_id
     *
     * @return the value of guu_sys_role.role_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role.role_id
     *
     * @param roleId the value for guu_sys_role.role_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role.role_name
     *
     * @return the value of guu_sys_role.role_name
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role.role_name
     *
     * @param roleName the value for guu_sys_role.role_name
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role.role_code
     *
     * @return the value of guu_sys_role.role_code
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role.role_code
     *
     * @param roleCode the value for guu_sys_role.role_code
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role.creat_user
     *
     * @return the value of guu_sys_role.creat_user
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getCreatUser() {
        return creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role.creat_user
     *
     * @param creatUser the value for guu_sys_role.creat_user
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setCreatUser(String creatUser) {
        this.creatUser = creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role.creat_time
     *
     * @return the value of guu_sys_role.creat_time
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role.creat_time
     *
     * @param creatTime the value for guu_sys_role.creat_time
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role.role_status
     *
     * @return the value of guu_sys_role.role_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Integer getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role.role_status
     *
     * @param roleStatus the value for guu_sys_role.role_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRoleStatus(Integer roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role.issys
     *
     * @return the value of guu_sys_role.issys
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Integer getIssys() {
        return issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role.issys
     *
     * @param issys the value for guu_sys_role.issys
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setIssys(Integer issys) {
        this.issys = issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role.remark
     *
     * @return the value of guu_sys_role.remark
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role.remark
     *
     * @param remark the value for guu_sys_role.remark
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}