package cn.net.guu.system.model;

public class SysRoleAccess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_access.role_access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String roleAccessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_access.role_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_access.access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String accessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_access.ua_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Integer uaStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_access.role_access_id
     *
     * @return the value of guu_sys_role_access.role_access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getRoleAccessId() {
        return roleAccessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_access.role_access_id
     *
     * @param roleAccessId the value for guu_sys_role_access.role_access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRoleAccessId(String roleAccessId) {
        this.roleAccessId = roleAccessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_access.role_id
     *
     * @return the value of guu_sys_role_access.role_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_access.role_id
     *
     * @param roleId the value for guu_sys_role_access.role_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_access.access_id
     *
     * @return the value of guu_sys_role_access.access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getAccessId() {
        return accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_access.access_id
     *
     * @param accessId the value for guu_sys_role_access.access_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setAccessId(String accessId) {
        this.accessId = accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_access.ua_status
     *
     * @return the value of guu_sys_role_access.ua_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Integer getUaStatus() {
        return uaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_access.ua_status
     *
     * @param uaStatus the value for guu_sys_role_access.ua_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setUaStatus(Integer uaStatus) {
        this.uaStatus = uaStatus;
    }
}