package cn.net.guu.system.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import cn.net.guu.core.mappers.BaseExample;

public class SysResourcesExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public SysResourcesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andResourcesIdIsNull() {
            addCriterion("resources_id is null");
            return (Criteria) this;
        }

        public Criteria andResourcesIdIsNotNull() {
            addCriterion("resources_id is not null");
            return (Criteria) this;
        }

        public Criteria andResourcesIdEqualTo(String value) {
            addCriterion("resources_id =", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdNotEqualTo(String value) {
            addCriterion("resources_id <>", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdGreaterThan(String value) {
            addCriterion("resources_id >", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdGreaterThanOrEqualTo(String value) {
            addCriterion("resources_id >=", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdLessThan(String value) {
            addCriterion("resources_id <", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdLessThanOrEqualTo(String value) {
            addCriterion("resources_id <=", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdLike(String value) {
            addCriterion("resources_id like", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdNotLike(String value) {
            addCriterion("resources_id not like", value, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdIn(List<String> values) {
            addCriterion("resources_id in", values, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdNotIn(List<String> values) {
            addCriterion("resources_id not in", values, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdBetween(String value1, String value2) {
            addCriterion("resources_id between", value1, value2, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesIdNotBetween(String value1, String value2) {
            addCriterion("resources_id not between", value1, value2, "resourcesId");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeIsNull() {
            addCriterion("resources_code is null");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeIsNotNull() {
            addCriterion("resources_code is not null");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeEqualTo(String value) {
            addCriterion("resources_code =", value, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeNotEqualTo(String value) {
            addCriterion("resources_code <>", value, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeGreaterThan(String value) {
            addCriterion("resources_code >", value, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeGreaterThanOrEqualTo(String value) {
            addCriterion("resources_code >=", value, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeLessThan(String value) {
            addCriterion("resources_code <", value, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeLessThanOrEqualTo(String value) {
            addCriterion("resources_code <=", value, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeLike(String value) {
            addCriterion("resources_code like", value, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeNotLike(String value) {
            addCriterion("resources_code not like", value, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeIn(List<String> values) {
            addCriterion("resources_code in", values, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeNotIn(List<String> values) {
            addCriterion("resources_code not in", values, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeBetween(String value1, String value2) {
            addCriterion("resources_code between", value1, value2, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesCodeNotBetween(String value1, String value2) {
            addCriterion("resources_code not between", value1, value2, "resourcesCode");
            return (Criteria) this;
        }

        public Criteria andResourcesNameIsNull() {
            addCriterion("resources_name is null");
            return (Criteria) this;
        }

        public Criteria andResourcesNameIsNotNull() {
            addCriterion("resources_name is not null");
            return (Criteria) this;
        }

        public Criteria andResourcesNameEqualTo(String value) {
            addCriterion("resources_name =", value, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameNotEqualTo(String value) {
            addCriterion("resources_name <>", value, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameGreaterThan(String value) {
            addCriterion("resources_name >", value, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameGreaterThanOrEqualTo(String value) {
            addCriterion("resources_name >=", value, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameLessThan(String value) {
            addCriterion("resources_name <", value, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameLessThanOrEqualTo(String value) {
            addCriterion("resources_name <=", value, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameLike(String value) {
            addCriterion("resources_name like", value, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameNotLike(String value) {
            addCriterion("resources_name not like", value, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameIn(List<String> values) {
            addCriterion("resources_name in", values, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameNotIn(List<String> values) {
            addCriterion("resources_name not in", values, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameBetween(String value1, String value2) {
            addCriterion("resources_name between", value1, value2, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesNameNotBetween(String value1, String value2) {
            addCriterion("resources_name not between", value1, value2, "resourcesName");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlIsNull() {
            addCriterion("resources_url is null");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlIsNotNull() {
            addCriterion("resources_url is not null");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlEqualTo(String value) {
            addCriterion("resources_url =", value, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlNotEqualTo(String value) {
            addCriterion("resources_url <>", value, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlGreaterThan(String value) {
            addCriterion("resources_url >", value, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlGreaterThanOrEqualTo(String value) {
            addCriterion("resources_url >=", value, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlLessThan(String value) {
            addCriterion("resources_url <", value, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlLessThanOrEqualTo(String value) {
            addCriterion("resources_url <=", value, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlLike(String value) {
            addCriterion("resources_url like", value, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlNotLike(String value) {
            addCriterion("resources_url not like", value, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlIn(List<String> values) {
            addCriterion("resources_url in", values, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlNotIn(List<String> values) {
            addCriterion("resources_url not in", values, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlBetween(String value1, String value2) {
            addCriterion("resources_url between", value1, value2, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesUrlNotBetween(String value1, String value2) {
            addCriterion("resources_url not between", value1, value2, "resourcesUrl");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeIsNull() {
            addCriterion("resources_type is null");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeIsNotNull() {
            addCriterion("resources_type is not null");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeEqualTo(String value) {
            addCriterion("resources_type =", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeNotEqualTo(String value) {
            addCriterion("resources_type <>", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeGreaterThan(String value) {
            addCriterion("resources_type >", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeGreaterThanOrEqualTo(String value) {
            addCriterion("resources_type >=", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeLessThan(String value) {
            addCriterion("resources_type <", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeLessThanOrEqualTo(String value) {
            addCriterion("resources_type <=", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeLike(String value) {
            addCriterion("resources_type like", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeNotLike(String value) {
            addCriterion("resources_type not like", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeIn(List<String> values) {
            addCriterion("resources_type in", values, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeNotIn(List<String> values) {
            addCriterion("resources_type not in", values, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeBetween(String value1, String value2) {
            addCriterion("resources_type between", value1, value2, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeNotBetween(String value1, String value2) {
            addCriterion("resources_type not between", value1, value2, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("creat_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("creat_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterion("creat_time =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterion("creat_time <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterion("creat_time >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("creat_time >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterion("creat_time <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterion("creat_time <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterion("creat_time in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterion("creat_time not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterion("creat_time between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterion("creat_time not between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(String value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(String value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(String value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(String value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(String value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLike(String value) {
            addCriterion("parent_id like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotLike(String value) {
            addCriterion("parent_id not like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<String> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<String> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(String value1, String value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(String value1, String value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andResourcesDescIsNull() {
            addCriterion("resources_desc is null");
            return (Criteria) this;
        }

        public Criteria andResourcesDescIsNotNull() {
            addCriterion("resources_desc is not null");
            return (Criteria) this;
        }

        public Criteria andResourcesDescEqualTo(String value) {
            addCriterion("resources_desc =", value, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescNotEqualTo(String value) {
            addCriterion("resources_desc <>", value, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescGreaterThan(String value) {
            addCriterion("resources_desc >", value, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescGreaterThanOrEqualTo(String value) {
            addCriterion("resources_desc >=", value, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescLessThan(String value) {
            addCriterion("resources_desc <", value, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescLessThanOrEqualTo(String value) {
            addCriterion("resources_desc <=", value, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescLike(String value) {
            addCriterion("resources_desc like", value, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescNotLike(String value) {
            addCriterion("resources_desc not like", value, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescIn(List<String> values) {
            addCriterion("resources_desc in", values, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescNotIn(List<String> values) {
            addCriterion("resources_desc not in", values, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescBetween(String value1, String value2) {
            addCriterion("resources_desc between", value1, value2, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResourcesDescNotBetween(String value1, String value2) {
            addCriterion("resources_desc not between", value1, value2, "resourcesDesc");
            return (Criteria) this;
        }

        public Criteria andResStatusIsNull() {
            addCriterion("res_status is null");
            return (Criteria) this;
        }

        public Criteria andResStatusIsNotNull() {
            addCriterion("res_status is not null");
            return (Criteria) this;
        }

        public Criteria andResStatusEqualTo(Integer value) {
            addCriterion("res_status =", value, "resStatus");
            return (Criteria) this;
        }

        public Criteria andResStatusNotEqualTo(Integer value) {
            addCriterion("res_status <>", value, "resStatus");
            return (Criteria) this;
        }

        public Criteria andResStatusGreaterThan(Integer value) {
            addCriterion("res_status >", value, "resStatus");
            return (Criteria) this;
        }

        public Criteria andResStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("res_status >=", value, "resStatus");
            return (Criteria) this;
        }

        public Criteria andResStatusLessThan(Integer value) {
            addCriterion("res_status <", value, "resStatus");
            return (Criteria) this;
        }

        public Criteria andResStatusLessThanOrEqualTo(Integer value) {
            addCriterion("res_status <=", value, "resStatus");
            return (Criteria) this;
        }

        public Criteria andResStatusIn(List<Integer> values) {
            addCriterion("res_status in", values, "resStatus");
            return (Criteria) this;
        }

        public Criteria andResStatusNotIn(List<Integer> values) {
            addCriterion("res_status not in", values, "resStatus");
            return (Criteria) this;
        }

        public Criteria andResStatusBetween(Integer value1, Integer value2) {
            addCriterion("res_status between", value1, value2, "resStatus");
            return (Criteria) this;
        }

        public Criteria andResStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("res_status not between", value1, value2, "resStatus");
            return (Criteria) this;
        }

        public Criteria andIssysIsNull() {
            addCriterion("issys is null");
            return (Criteria) this;
        }

        public Criteria andIssysIsNotNull() {
            addCriterion("issys is not null");
            return (Criteria) this;
        }

        public Criteria andIssysEqualTo(Integer value) {
            addCriterion("issys =", value, "issys");
            return (Criteria) this;
        }

        public Criteria andIssysNotEqualTo(Integer value) {
            addCriterion("issys <>", value, "issys");
            return (Criteria) this;
        }

        public Criteria andIssysGreaterThan(Integer value) {
            addCriterion("issys >", value, "issys");
            return (Criteria) this;
        }

        public Criteria andIssysGreaterThanOrEqualTo(Integer value) {
            addCriterion("issys >=", value, "issys");
            return (Criteria) this;
        }

        public Criteria andIssysLessThan(Integer value) {
            addCriterion("issys <", value, "issys");
            return (Criteria) this;
        }

        public Criteria andIssysLessThanOrEqualTo(Integer value) {
            addCriterion("issys <=", value, "issys");
            return (Criteria) this;
        }

        public Criteria andIssysIn(List<Integer> values) {
            addCriterion("issys in", values, "issys");
            return (Criteria) this;
        }

        public Criteria andIssysNotIn(List<Integer> values) {
            addCriterion("issys not in", values, "issys");
            return (Criteria) this;
        }

        public Criteria andIssysBetween(Integer value1, Integer value2) {
            addCriterion("issys between", value1, value2, "issys");
            return (Criteria) this;
        }

        public Criteria andIssysNotBetween(Integer value1, Integer value2) {
            addCriterion("issys not between", value1, value2, "issys");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_sys_resources
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 23 23:14:26 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_sys_resources
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}