package cn.net.guu.system.model;

import java.util.ArrayList;
import java.util.List;

import cn.net.guu.core.mappers.BaseExample;

public class SysRoleAccessExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public SysRoleAccessExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleAccessIdIsNull() {
            addCriterion("role_access_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdIsNotNull() {
            addCriterion("role_access_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdEqualTo(String value) {
            addCriterion("role_access_id =", value, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdNotEqualTo(String value) {
            addCriterion("role_access_id <>", value, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdGreaterThan(String value) {
            addCriterion("role_access_id >", value, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdGreaterThanOrEqualTo(String value) {
            addCriterion("role_access_id >=", value, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdLessThan(String value) {
            addCriterion("role_access_id <", value, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdLessThanOrEqualTo(String value) {
            addCriterion("role_access_id <=", value, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdLike(String value) {
            addCriterion("role_access_id like", value, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdNotLike(String value) {
            addCriterion("role_access_id not like", value, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdIn(List<String> values) {
            addCriterion("role_access_id in", values, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdNotIn(List<String> values) {
            addCriterion("role_access_id not in", values, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdBetween(String value1, String value2) {
            addCriterion("role_access_id between", value1, value2, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleAccessIdNotBetween(String value1, String value2) {
            addCriterion("role_access_id not between", value1, value2, "roleAccessId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(String value) {
            addCriterion("role_id =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(String value) {
            addCriterion("role_id <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(String value) {
            addCriterion("role_id >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(String value) {
            addCriterion("role_id >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(String value) {
            addCriterion("role_id <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(String value) {
            addCriterion("role_id <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLike(String value) {
            addCriterion("role_id like", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotLike(String value) {
            addCriterion("role_id not like", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<String> values) {
            addCriterion("role_id in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<String> values) {
            addCriterion("role_id not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(String value1, String value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(String value1, String value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andAccessIdIsNull() {
            addCriterion("access_id is null");
            return (Criteria) this;
        }

        public Criteria andAccessIdIsNotNull() {
            addCriterion("access_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccessIdEqualTo(String value) {
            addCriterion("access_id =", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdNotEqualTo(String value) {
            addCriterion("access_id <>", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdGreaterThan(String value) {
            addCriterion("access_id >", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdGreaterThanOrEqualTo(String value) {
            addCriterion("access_id >=", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdLessThan(String value) {
            addCriterion("access_id <", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdLessThanOrEqualTo(String value) {
            addCriterion("access_id <=", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdLike(String value) {
            addCriterion("access_id like", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdNotLike(String value) {
            addCriterion("access_id not like", value, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdIn(List<String> values) {
            addCriterion("access_id in", values, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdNotIn(List<String> values) {
            addCriterion("access_id not in", values, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdBetween(String value1, String value2) {
            addCriterion("access_id between", value1, value2, "accessId");
            return (Criteria) this;
        }

        public Criteria andAccessIdNotBetween(String value1, String value2) {
            addCriterion("access_id not between", value1, value2, "accessId");
            return (Criteria) this;
        }

        public Criteria andUaStatusIsNull() {
            addCriterion("ua_status is null");
            return (Criteria) this;
        }

        public Criteria andUaStatusIsNotNull() {
            addCriterion("ua_status is not null");
            return (Criteria) this;
        }

        public Criteria andUaStatusEqualTo(Integer value) {
            addCriterion("ua_status =", value, "uaStatus");
            return (Criteria) this;
        }

        public Criteria andUaStatusNotEqualTo(Integer value) {
            addCriterion("ua_status <>", value, "uaStatus");
            return (Criteria) this;
        }

        public Criteria andUaStatusGreaterThan(Integer value) {
            addCriterion("ua_status >", value, "uaStatus");
            return (Criteria) this;
        }

        public Criteria andUaStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("ua_status >=", value, "uaStatus");
            return (Criteria) this;
        }

        public Criteria andUaStatusLessThan(Integer value) {
            addCriterion("ua_status <", value, "uaStatus");
            return (Criteria) this;
        }

        public Criteria andUaStatusLessThanOrEqualTo(Integer value) {
            addCriterion("ua_status <=", value, "uaStatus");
            return (Criteria) this;
        }

        public Criteria andUaStatusIn(List<Integer> values) {
            addCriterion("ua_status in", values, "uaStatus");
            return (Criteria) this;
        }

        public Criteria andUaStatusNotIn(List<Integer> values) {
            addCriterion("ua_status not in", values, "uaStatus");
            return (Criteria) this;
        }

        public Criteria andUaStatusBetween(Integer value1, Integer value2) {
            addCriterion("ua_status between", value1, value2, "uaStatus");
            return (Criteria) this;
        }

        public Criteria andUaStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("ua_status not between", value1, value2, "uaStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 23 23:14:26 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guu_sys_role_access
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}