package cn.net.guu.system.model;

import java.util.Date;

public class SysResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.resources_code
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String resourcesCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.resources_name
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String resourcesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.resources_url
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String resourcesUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.resources_type
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String resourcesType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.creat_time
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.parent_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.resources_desc
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String resourcesDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.res_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Integer resStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.issys
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Integer issys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_resources.remark
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.resources_id
     *
     * @return the value of guu_sys_resources.resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.resources_id
     *
     * @param resourcesId the value for guu_sys_resources.resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.resources_code
     *
     * @return the value of guu_sys_resources.resources_code
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getResourcesCode() {
        return resourcesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.resources_code
     *
     * @param resourcesCode the value for guu_sys_resources.resources_code
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setResourcesCode(String resourcesCode) {
        this.resourcesCode = resourcesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.resources_name
     *
     * @return the value of guu_sys_resources.resources_name
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getResourcesName() {
        return resourcesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.resources_name
     *
     * @param resourcesName the value for guu_sys_resources.resources_name
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setResourcesName(String resourcesName) {
        this.resourcesName = resourcesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.resources_url
     *
     * @return the value of guu_sys_resources.resources_url
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getResourcesUrl() {
        return resourcesUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.resources_url
     *
     * @param resourcesUrl the value for guu_sys_resources.resources_url
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setResourcesUrl(String resourcesUrl) {
        this.resourcesUrl = resourcesUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.resources_type
     *
     * @return the value of guu_sys_resources.resources_type
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getResourcesType() {
        return resourcesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.resources_type
     *
     * @param resourcesType the value for guu_sys_resources.resources_type
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setResourcesType(String resourcesType) {
        this.resourcesType = resourcesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.creat_time
     *
     * @return the value of guu_sys_resources.creat_time
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.creat_time
     *
     * @param creatTime the value for guu_sys_resources.creat_time
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.parent_id
     *
     * @return the value of guu_sys_resources.parent_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.parent_id
     *
     * @param parentId the value for guu_sys_resources.parent_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.resources_desc
     *
     * @return the value of guu_sys_resources.resources_desc
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getResourcesDesc() {
        return resourcesDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.resources_desc
     *
     * @param resourcesDesc the value for guu_sys_resources.resources_desc
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setResourcesDesc(String resourcesDesc) {
        this.resourcesDesc = resourcesDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.res_status
     *
     * @return the value of guu_sys_resources.res_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Integer getResStatus() {
        return resStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.res_status
     *
     * @param resStatus the value for guu_sys_resources.res_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setResStatus(Integer resStatus) {
        this.resStatus = resStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.issys
     *
     * @return the value of guu_sys_resources.issys
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Integer getIssys() {
        return issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.issys
     *
     * @param issys the value for guu_sys_resources.issys
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setIssys(Integer issys) {
        this.issys = issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_resources.remark
     *
     * @return the value of guu_sys_resources.remark
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_resources.remark
     *
     * @param remark the value for guu_sys_resources.remark
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}