package cn.net.guu.system.model;

public class SysRoleAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_authority.role_authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String roleAuthorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_authority.role_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_authority.authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private String authorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_authority.ra_status
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    private Integer raStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_authority.role_authority_id
     *
     * @return the value of guu_sys_role_authority.role_authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getRoleAuthorityId() {
        return roleAuthorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_authority.role_authority_id
     *
     * @param roleAuthorityId the value for guu_sys_role_authority.role_authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setRoleAuthorityId(String roleAuthorityId) {
        this.roleAuthorityId = roleAuthorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_authority.role_id
     *
     * @return the value of guu_sys_role_authority.role_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_authority.role_id
     *
     * @param roleId the value for guu_sys_role_authority.role_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_authority.authority_id
     *
     * @return the value of guu_sys_role_authority.authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_authority.authority_id
     *
     * @param authorityId the value for guu_sys_role_authority.authority_id
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_authority.ra_status
     *
     * @return the value of guu_sys_role_authority.ra_status
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public Integer getRaStatus() {
        return raStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_authority.ra_status
     *
     * @param raStatus the value for guu_sys_role_authority.ra_status
     *
     * @mbggenerated Sat Aug 02 00:13:15 CST 2014
     */
    public void setRaStatus(Integer raStatus) {
        this.raStatus = raStatus;
    }
}