package cn.net.guu.system.model;

public class SysRoleResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_resources.role_authority_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String roleAuthorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_resources.role_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_resources.resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private String resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guu_sys_role_resources.ra_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    private Integer raStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_resources.role_authority_id
     *
     * @return the value of guu_sys_role_resources.role_authority_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getRoleAuthorityId() {
        return roleAuthorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_resources.role_authority_id
     *
     * @param roleAuthorityId the value for guu_sys_role_resources.role_authority_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRoleAuthorityId(String roleAuthorityId) {
        this.roleAuthorityId = roleAuthorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_resources.role_id
     *
     * @return the value of guu_sys_role_resources.role_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_resources.role_id
     *
     * @param roleId the value for guu_sys_role_resources.role_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_resources.resources_id
     *
     * @return the value of guu_sys_role_resources.resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_resources.resources_id
     *
     * @param resourcesId the value for guu_sys_role_resources.resources_id
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guu_sys_role_resources.ra_status
     *
     * @return the value of guu_sys_role_resources.ra_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public Integer getRaStatus() {
        return raStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guu_sys_role_resources.ra_status
     *
     * @param raStatus the value for guu_sys_role_resources.ra_status
     *
     * @mbggenerated Wed Jul 23 23:14:26 CST 2014
     */
    public void setRaStatus(Integer raStatus) {
        this.raStatus = raStatus;
    }
}