package cn.net.guu.system.model;

import java.util.Collection;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import cn.net.guu.core.config.CommonKey;

public class SysUser implements UserDetails
{

	/** serialVersionUID */
	private static final long serialVersionUID = CommonKey.SERIALVERSIONUID;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.user_id
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.user_name
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.login_name
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String loginName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.login_password
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String loginPassword;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.email
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.photo
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String photo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.phone
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.telphone
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String telphone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.creat_time
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	@DateTimeFormat(pattern = CommonKey.DATE_FORMAR_YYYY_MM_DD_HH_mm_ss)
	private Date creatTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.creat_user
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String creatUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.user_type
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String userType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.role_id
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String roleId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.role_code
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String roleCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.user_status
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private Integer userStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.issys
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private Integer issys;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.user_desc
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String userDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.remark
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guu_sys_user.content
	 * 
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.user_id
	 * 
	 * @return the value of guu_sys_user.user_id
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getUserId()
	{
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.user_id
	 * 
	 * @param userId
	 *            the value for guu_sys_user.user_id
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.user_name
	 * 
	 * @return the value of guu_sys_user.user_name
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getUserName()
	{
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.user_name
	 * 
	 * @param userName
	 *            the value for guu_sys_user.user_name
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setUserName(String userName)
	{
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * guu_sys_user.login_name
	 * 
	 * @return the value of guu_sys_user.login_name
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getLoginName()
	{
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.login_name
	 * 
	 * @param loginName
	 *            the value for guu_sys_user.login_name
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setLoginName(String loginName)
	{
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * guu_sys_user.login_password
	 * 
	 * @return the value of guu_sys_user.login_password
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getLoginPassword()
	{
		return loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * guu_sys_user.login_password
	 * 
	 * @param loginPassword
	 *            the value for guu_sys_user.login_password
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setLoginPassword(String loginPassword)
	{
		this.loginPassword = loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.email
	 * 
	 * @return the value of guu_sys_user.email
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.email
	 * 
	 * @param email
	 *            the value for guu_sys_user.email
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setEmail(String email)
	{
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.photo
	 * 
	 * @return the value of guu_sys_user.photo
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getPhoto()
	{
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.photo
	 * 
	 * @param photo
	 *            the value for guu_sys_user.photo
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setPhoto(String photo)
	{
		this.photo = photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.phone
	 * 
	 * @return the value of guu_sys_user.phone
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getPhone()
	{
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.phone
	 * 
	 * @param phone
	 *            the value for guu_sys_user.phone
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setPhone(String phone)
	{
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.telphone
	 * 
	 * @return the value of guu_sys_user.telphone
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getTelphone()
	{
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.telphone
	 * 
	 * @param telphone
	 *            the value for guu_sys_user.telphone
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setTelphone(String telphone)
	{
		this.telphone = telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * guu_sys_user.creat_time
	 * 
	 * @return the value of guu_sys_user.creat_time
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public Date getCreatTime()
	{
		return creatTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.creat_time
	 * 
	 * @param creatTime
	 *            the value for guu_sys_user.creat_time
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setCreatTime(Date creatTime)
	{
		this.creatTime = creatTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * guu_sys_user.creat_user
	 * 
	 * @return the value of guu_sys_user.creat_user
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getCreatUser()
	{
		return creatUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.creat_user
	 * 
	 * @param creatUser
	 *            the value for guu_sys_user.creat_user
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setCreatUser(String creatUser)
	{
		this.creatUser = creatUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.user_type
	 * 
	 * @return the value of guu_sys_user.user_type
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getUserType()
	{
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.user_type
	 * 
	 * @param userType
	 *            the value for guu_sys_user.user_type
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setUserType(String userType)
	{
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.role_id
	 * 
	 * @return the value of guu_sys_user.role_id
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getRoleId()
	{
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.role_id
	 * 
	 * @param roleId
	 *            the value for guu_sys_user.role_id
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setRoleId(String roleId)
	{
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.role_code
	 * 
	 * @return the value of guu_sys_user.role_code
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getRoleCode()
	{
		return roleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.role_code
	 * 
	 * @param roleCode
	 *            the value for guu_sys_user.role_code
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setRoleCode(String roleCode)
	{
		this.roleCode = roleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * guu_sys_user.user_status
	 * 
	 * @return the value of guu_sys_user.user_status
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public Integer getUserStatus()
	{
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.user_status
	 * 
	 * @param userStatus
	 *            the value for guu_sys_user.user_status
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setUserStatus(Integer userStatus)
	{
		this.userStatus = userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.issys
	 * 
	 * @return the value of guu_sys_user.issys
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public Integer getIssys()
	{
		return issys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.issys
	 * 
	 * @param issys
	 *            the value for guu_sys_user.issys
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setIssys(Integer issys)
	{
		this.issys = issys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.user_desc
	 * 
	 * @return the value of guu_sys_user.user_desc
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getUserDesc()
	{
		return userDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.user_desc
	 * 
	 * @param userDesc
	 *            the value for guu_sys_user.user_desc
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setUserDesc(String userDesc)
	{
		this.userDesc = userDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.remark
	 * 
	 * @return the value of guu_sys_user.remark
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getRemark()
	{
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.remark
	 * 
	 * @param remark
	 *            the value for guu_sys_user.remark
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guu_sys_user.content
	 * 
	 * @return the value of guu_sys_user.content
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public String getContent()
	{
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guu_sys_user.content
	 * 
	 * @param content
	 *            the value for guu_sys_user.content
	 * @mbggenerated Thu Mar 19 00:38:59 CST 2015
	 */
	public void setContent(String content)
	{
		this.content = content;
	}

	private Collection<GrantedAuthority> authorities; // 权限集合

	private boolean accountNonExpired; // 是否过期
	private boolean accountNonLocked; // 是否锁住
	private boolean credentialsNonExpired;
	private boolean enabled; // 是否可用

	public SysUser()
	{

	}

	public SysUser(String userName, String password, boolean enabled, boolean accountNonExpired, boolean accoutNonLocked,
			boolean credentailsNonExpired, Collection<GrantedAuthority> authorities)
	{
		this.loginName = userName;
		this.loginPassword = password;
		this.enabled = enabled;
		this.accountNonExpired = accountNonExpired;
		this.accountNonLocked = accoutNonLocked;
		this.credentialsNonExpired = credentailsNonExpired;
		this.authorities = authorities;
	}

	// 获取当前登录用户详细信息必须重写hashCode和equals方法
	public int hashCode()
	{
		return this.getLoginName().hashCode();
	}

	public boolean equals(Object object)
	{
		boolean flag = false;
		if (object instanceof UserDetails)
		{
			UserDetails user = (UserDetails) object;
			if (user.getUsername().equals(this.getLoginName()))
				flag = true;
		}
		return flag;
	}

	public Collection<GrantedAuthority> getAuthorities()
	{
		return authorities;
	}

	public void setAuthorities(Collection<GrantedAuthority> authorities)
	{
		this.authorities = authorities;
	}

	public boolean isAccountNonExpired()
	{
		return accountNonExpired;
	}

	public void setAccountNonExpired(boolean accountNonExpired)
	{
		this.accountNonExpired = accountNonExpired;
	}

	public boolean isAccountNonLocked()
	{
		return accountNonLocked;
	}

	public void setAccountNonLocked(boolean accountNonLocked)
	{
		this.accountNonLocked = accountNonLocked;
	}

	public boolean isCredentialsNonExpired()
	{
		return credentialsNonExpired;
	}

	public void setCredentialsNonExpired(boolean credentialsNonExpired)
	{
		this.credentialsNonExpired = credentialsNonExpired;
	}

	public boolean isEnabled()
	{
		return enabled;
	}

	public void setEnabled(boolean enabled)
	{
		this.enabled = enabled;
	}

	/**
	 * 用户包含的角�?
	 */
	private List<SysRole> userRoles;

	public List<SysRole> getUserRoles()
	{
		return userRoles;
	}

	public void setUserRoles(List<SysRole> userRoles)
	{
		this.userRoles = userRoles;
	}

	/**
	 * 用户包含的访问资源信�?
	 */
	private List<SysResources> userResources;

	public List<SysResources> getUserResources()
	{
		return userResources;
	}

	public void setUserResources(List<SysResources> userResources)
	{
		this.userResources = userResources;
	}

	public String getUsername()
	{
		return loginName;
	}

	public String getPassword()
	{
		return loginPassword;
	}

}